go.mod
go.sum

- Contains table alias bug fix
- Contains support for identifiers wrapped by double quotes, backticks or square brackets

Updates the parser

---

internal/router/middlewares/authentication_test.go
internal/tableland/impl/mesa.go
internal/tableland/impl/mesa_instrumented.go
internal/tableland/tableland.go
pkg/sqlstore/impl/system_store_instrumented.go
tableland-openapi-spec.yaml

This is a first try at writing production go, so any feedback would be really appreciated.  Hopefully it satisfies the Validator's part of https://www.notion.so/textile/Add-enableTestnetRPCRelay-flag-in-JS-SDK-d6ccf9e045bb4c54a43bbb0b0e78483d

Add rpc endpoint validateWriteQuery

---

cmd/toolkit/main.go
cmd/toolkit/smart_contract.go
tableland-openapi-spec.yaml

Also, removes the param `caller` from open api spec.

Adds SetController call to toolkit

---

internal/router/router.go

The `UserController` was taking as a dependency an instrumented `mesa`, which generates a correlation between the `/query` REST API and the `RunReadQuery` JSON-RPC. This is because `/query` calls the RPC method internally.
This has an undesired side-effect of correlating both RPCs in the metrics:
Calls that come from `/query` should only be reflected in `/query`, not indirectly in `RunReadQuery`.
The fix here is to avoid using the instrumented `mesa`, thus any call from `UserController` to the `mesa` service wouldn't _pollute_ the middleware metrics.

router: use uninstrumented mesa for UserController

---

LICENSE
LICENSE-APACHE
Makefile
README.md

This PR:
- Updates the README. See [rendered](https://github.com/tablelandnetwork/go-tableland/blob/837fc2f078d56c09515b878bc91c9a1da08ab1f4/README.md).
- Add licenses.
- Clean up some other things.

Update README & Licenses

---

docker/deployed/staging/api/config.json
docker/deployed/testnet/api/config.json
docker/local/api/config.json
internal/system/impl/sqlstore.go
internal/system/impl/sqlstore_test.go

Fixes external url

---

pkg/parsing/impl/validator.go
pkg/parsing/impl/validator_test.go
pkg/parsing/query_validator.go

Improves message when a not allowed prefix is used

---

pkg/eventprocessor/eventfeed/impl/eventfeed.go

Signed-off-by: Ignacio Hagopian <jsign.uy@gmail.com>

eventfeed: always consume the subscription

---

docker/observability/grafana/provisioning/dashboards/validator-dashbaord.json
pkg/eventprocessor/impl/eventprocessor.go
pkg/eventprocessor/impl/metrics.go

This PR adjusts some metrics collection and changed the dashboard.

eventprocessor: adjust metric

---

docker/deployed/testnet/healthbot/config.json

Signed-off-by: Ignacio Hagopian <jsign.uy@gmail.com>

healthbot: fix missing comma in config file

---

pkg/eventprocessor/impl/executor/impl/executor.go

The `Executor` had two missing things:
1. Close the db when `Close()` is called. (I wonder if this contributed to WAL prunning checkpointing delays)
2. There was a subtle race between `Close()` and getting a lock to enforce serial execution (will be explained in comments).

executor: improve closing

---

cmd/healthbot/counterprobe/counterprobe.go

Signed-off-by: Aaron Sutula <asutula@users.noreply.github.com>

Correct output for counterprobe

---

internal/router/controllers/user.go
internal/router/controllers/user_test.go

This is to provide compatibility with urls using `mode=list` for NFT metadata

Use extract for mode=list

---

docker/deployed/docker-compose.observability.yml

Updates the Docker image for Grafana.
NA
NA
NA

docker/grafana: update grafana

---

docker/deployed/staging/healthbot/config.json
docker/deployed/testnet/healthbot/config.json

Adjusts healthbot check interval config to check at a slower pace
Funds are draining too fast and goerli is scarce 
na
na

Adjusts healthbot to check at a slower pace

---

pkg/client/chains.go

Fix Arbitrum URL in Client

---

.github/CODEOWNERS
.golangci.yml
buildinfo/buildinfo.go
cmd/api/main.go
internal/router/controllers/user.go
pkg/eventprocessor/impl/eventprocessor.go
pkg/eventprocessor/impl/eventprocessor_replayhistory_test.go
pkg/eventprocessor/impl/executor/executor.go
pkg/telemetry/chainscollector/chainscollector.go
pkg/telemetry/metrics.go
pkg/telemetry/storage/db_test.go
pkg/telemetry/telemetry.go
pkg/telemetry/telemetry_test.go

Closes #386.
NA
I was going to bundle this work as part of my PR to publish chain events as metrics, but I realized it might be better to separate both to simplify the review.
NA.

Refactor metrics to have a simplified API

---

docker/Makefile

Addresses some nits to avoid warnings described in https://github.com/tablelandnetwork/go-tableland/issues/404.
Closes #404.

docker/local: fixes

---

go.mod
go.sum
internal/system/impl/sqlstore_test.go
internal/tableland/impl/testdata/any_queries.csv
pkg/backup/backuper_test.go
pkg/backup/testdata/control.sql
pkg/eventprocessor/impl/eventprocessor_replayhistory_test.go
pkg/parsing/impl/validator_test.go
pkg/sqlstore/impl/system/store.go

Updates the parser library to commit `20a7e349a521`
Closes #393 
na
- Bumps SQLite version
- Updates expected hashes of `TestReplayProductionHistory` because parser changes break the historical state

Updates parser 

---

go.mod
go.sum
internal/tableland/impl/mesa_test.go
internal/tableland/impl/testdata/any_queries.csv
pkg/eventprocessor/impl/eventprocessor_replayhistory_test.go

Update parser library to most recent commit `863bbd9f65273f3aef99101139a0f63a58a8d98e`
Changes included:
- Drop support for ANY

parser: drop support for ANY

---

internal/router/controllers/apiv1/api_query.go
internal/router/controllers/apiv1/routers.go
internal/router/router.go

Updates to the spec change https://github.com/tablelandnetwork/docs/pull/49#event-8001105471
NA
Mostly `make gen-api-v1` and update the handler name in `router.go`.
NA

internal/router: update spec

---

internal/router/controllers/system.go

Return `Content-Type: application/json` in responses that have a JSON body.
NA
NA

controller/v1: return content-type when body isn't empty

---

internal/system/impl/sqlstore.go
internal/system/impl/sqlstore_test.go

animation_url: revert workaround

---

pkg/tables/impl/ethereum/client.go

The `ethclient` was using the previous gas model to configure fees. This was a bit problematic only in Ethereum Goerli that has gas spikes and is less predictable if not "thought" in regards of the baseFee.
This has been running in testnet for the weekend and looks like it improved the situation (no more problems reg stuck txns).
NA
NA
NA

ethclient: use EIP-1559 for gas

---

go.mod
go.sum

bump `github.com/klauspost/compress` to v1.16.3

Update compress library

---

docker/deployed/mainnet/api/config.json
docker/deployed/testnet/api/config.json
docker/deployed/testnet/healthbot/config.json

Update polling and receipt timeouts to align with Filecoin blocktimes.

Change timeouts for filecoin

---

go.mod
go.sum
pkg/eventprocessor/impl/eventprocessor_replayhistory_test.go
pkg/parsing/impl/validator_test.go

See https://github.com/tablelandnetwork/go-sqlparser/pull/54

fix table's name validation

---

README.md

Closes #539
Addresses out of date validator instructions. 
Morning discussion in Discord and responding to a developer support tix

fix(docs): clear intro line, updated validator instructions

---

README.md
cmd/api/main.go
docker/deployed/testnet/healthbot/config.json
internal/gateway/gateway.go
internal/gateway/impl/gateway_store.go
internal/router/controllers/apiv1/model_transaction_receipt.go
internal/router/controllers/controller.go
internal/router/controllers/controller_test.go
internal/tableland/impl/tableland_test.go
pkg/database/db/models.go
pkg/database/db/receipt.sql.go
pkg/database/migrations/005_receipttableids.down.sql
pkg/database/migrations/005_receipttableids.up.sql
pkg/database/migrations/migrations.go
pkg/eventprocessor/eventprocessor.go
pkg/eventprocessor/impl/eventprocessor.go
pkg/eventprocessor/impl/eventprocessor_replayhistory_test.go
pkg/eventprocessor/impl/eventprocessor_test.go
pkg/eventprocessor/impl/executor/executor.go
pkg/eventprocessor/impl/executor/impl/blockscope.go
pkg/eventprocessor/impl/executor/impl/txnscope.go
pkg/tables/tables.go

Preparation for v1.3.2 release
- #564 
- #563 
- #549

Prepare Release 1.3.2 (Ship 4b)

---

go.mod
go.sum

Updates parser to include changes from https://github.com/tablelandnetwork/go-sqlparser/pull/56

updates parser

---

go.mod
go.sum

Updates parser to remove HAVING restriction in INSERT with SELECT

removes HAVING restriction in INSERT with SELECT

---

docker/deployed/testnet/healthbot/config.json

Removes healthbot config for Filecoin Hyperspace since we have removed it in #580

Remove healthbot config for hyperspace

---

go.mod
go.sum

See https://github.com/tablelandnetwork/go-sqlparser/pull/61

bumps parser

---

pkg/client/v1/README.md

Adds a Readme file for Tableland Client with some examples showing usage.

[GOT-104] Add readme for the tableland client

---

internal/router/controllers/controller.go
internal/router/controllers/controller_test.go
pkg/client/v1/README.md

Release v1.7.0 preparation. Contains:
- https://github.com/tablelandnetwork/go-tableland/pull/588
- https://github.com/tablelandnetwork/go-tableland/pull/587

Prepare Release v1.7.0

---

pkg/eventprocessor/eventfeed/impl/eventfeed.go

Another increase of timeout because glif is timing out. Looks like the request is taking a minute

increase timeout filter logs

---

cmd/api/config.go
cmd/api/main.go
docker/deployed/mainnet/api/config.json
docker/deployed/staging/api/config.json
docker/deployed/testnet/api/config.json
internal/router/middlewares/ratelim.go
internal/router/middlewares/ratelim_test.go
internal/router/router.go
tests/fullstack/fullstack.go

PR that prepares for v1.8.0 release
Adds the following changes:
- https://github.com/tablelandnetwork/go-tableland/pull/599

Prepare for v1.8.0

---

pkg/eventprocessor/eventfeed/impl/eventfeed.go

increase timeout of header by number call

---

README.md

Swaps Arbitrum Goerli references to Arbitrum Sepolia.
N/A
N/A
N/A

docs: update README with arb goerli to sepolia

---

docker/deployed/testnet/healthbot/config.json

This was missed in #620. Had to drop Mumbai from the healthbot bot config otherwise it crashes.

Remove polygon mumbai from healthbot config
