tablelandnetwork/go-tableland

- cmd/api/main.go
- go.mod
- go.sum
- internal/router/controllers/user_test.go
We were missing disallowing `sqlite_` prefixes in table names. We had tests to exactly test this behavior, but in the main configuration we missed adding it.
> parser: disallow sqlite_ prefix in create tables

- pkg/eventprocessor/eventfeed/impl/eventfeed.go
The current SC allows emitting more than one event per txn, which isn't allowed today.
We need to handle this case since that would violate a PRIMARY KEY.
> eventfeed: only allow to process one event per txn

- internal/router/controllers/user.go
- internal/router/controllers/user_test.go
fixes panic: `interface conversion: interface {} is *interface {}, not **string`
afaict, conversion from `*interface {}` requires reflect to get at the underlying value type.
> fix prefix in table row gateway query

- docker/observability/grafana/provisioning/dashboards/validator-dashbaord.json
- go.mod
- go.sum
- pkg/sqlstore/impl/system/store.go
- pkg/sqlstore/impl/user/store.go
- pkg/txn/impl/processor.go
In this PR we add a library to wrap every opened connection to a `database/sql` driver to have a set of extra metrics at this layer. More about this at: https://github.com/XSAM/otelsql
I also updated the dashboard with:
- I collapsed in the same section the `HTTP requests` and `Public APIs` since they both are about the same things.
- I reordered sections a bit to put into the top more relevant ones.
- I renamed the section "SQL Store calls" with "SQL Database" and added two new tiles in the second row related to the new metrics of this wrapper (see screenshot below). You can see the live staging dashboard too.
(Not entirely interesting since it's staging)
> otel: automatically instrument database/sql connections

- cmd/healthbot/counterprobe/metrics.go
Adjust only observing new values in healthbot if they're true measurements to avoid false alarms.
Probably, we need to do something similar in other metrics in general (e.g: wallet balances). That might require some refactoring to make them pointers and use `nil` as the signal for no-value, or initialize them as -1 or similar.
> healthbot: avoid false first values

- docker/observability/grafana/provisioning/dashboards/validator-dashbaord.json
- go.mod
- go.sum
- internal/system/impl/sqlstore_instrumented.go
- internal/tableland/impl/mesa_instrumented.go
Now that we see more read volume, I'm adding some extra charts in the dashboard reg:
- #goroutines
- #live objects
- GC/s
The first two to spot any trends in leaked goroutines or mem objects.
Taking advantage and fixing other things:
- Better distinction between req/s and latency of REST paths vs JSON-RPC calls.
- We have a counter of any API response size, so we now we show ~"API output bytes / s"
- Fixed many legends
Also, I removed adding the `controller` in the metrics dimension. We aren't using this dimension, and it has the risk of exploding dimensions in Prometheus. If we come up with a chart that really uses the dimension, we can add it again.
> grafana/dashboard: add #goroutines, liveobjects and gc/s charts & general improvements

- cmd/api/main.go
- docker/deployed/testnet/api/config.json
- docker/deployed/testnet/healthbot/config.json
- internal/router/controllers/user.go
- internal/router/middlewares/logging.go
- internal/router/middlewares/ratelim.go
- internal/router/router.go
This PR:
- Adds a new logging middleware that logs any non-200 response. This will be useful to dig into some weird requests we're seeing.
- DIsable HTTP2, which Cloudflare proxy doesn't like produces 520 responses from their side.
- The User Controller was missing a `Msg` call in logs in an error path, not producing a particular log line.
- Reduce a bit the frequency of Kovan probes.
> Add logging middleware & disable HTTP2 & extra nits

- internal/tableland/impl/mesa_test.go
- pkg/eventprocessor/impl/eventprocessor.go
- pkg/txn/impl/processor.go
- pkg/txn/impl/processor_test.go
- pkg/txn/txn.go
The execution of a transfer event was not changing the table's owner in the registry table.
[Two tables were transferred on Goerli](https://goerli.etherscan.io/address/0x0C53611b433B486ec940334653F7756D75147dEA#tokentxnsErc721) (57 and 59) to address `0x0C53611b433B486ec940334653F7756D75147dEA`, but when executing the call `https://testnet.tableland.network/chain/5/tables/controller/0x0C53611b433B486ec940334653F7756D75147dEA` you could not see those tables listed.
The undesired behavior happened because of a missing logic when executing the transfer event logic. 
- I already synced from scratch locally (pointing to `testnet` contract) and the logic worked. 
- Deployed to staging
- Even after this PR is merged and deployed to `testnet`, we'll need to sync all events from scratch to pick up …
> Fixes transfer event execution

- docker/deployed/staging/api/config.json
- docker/deployed/testnet/api/config.json
This PR:
- Bumps rate-limiting to the original rate now that CF is doing the heavy lifting on bad cases.
- Bumps table row limit to 500k as decided in TPD.
> testnet: restore original rate limit

- cmd/api/main.go
I got a message from CF that we might be accepting TLS ciphers that aren't aligned with what they expect.
Now set ciphers to match [their official documentation](https://developers.cloudflare.com/ssl/origin-configuration/cipher-suites/) to see if this impacts them.
After we figure out if it does (or not), we can see later to revert or make this an optional flag. For now, take this as giving it a try to fix the 520 from CF.
> tls: tune configuration for CF

- go.mod
- go.sum
- pkg/parsing/impl/validator_test.go
REFERENCES is a keyword that is not allowed as identifier. This was causing the validator to be stuck.
Signed-off-by: Bruno Calza <brunoangelicalza@gmail.com>
> Updates to most recent version of the parser [stagingdeploy]

- cmd/api/config.go
- cmd/api/main.go
- docker/deployed/staging/api/config.json
- docker/deployed/testnet/api/config.json
- docker/local/api/config.json
- internal/chains/chains.go
- internal/tableland/impl/mesa.go
- internal/tableland/impl/mesa_test.go
- pkg/client/client_test.go
Adds a new config `AllowTransactionRelay` that applies to `RelayWriteQuery` and `SetController` RPC calls. 
The way to set this config is to set it to `true` for testnets and `false` for mainnets. That means that calls to `RelayWriteQuery` and `SetController` for mainnets won't get through (it will throw an error). 
This PR also refactors the way tests are setup in `mesa_test.go`. Check this [comment](https://github.com/tablelandnetwork/go-tableland/pull/210/files#r936031981).
> Adds AllowTransactionRelay config

- cmd/api/config.go
- cmd/api/main.go
- docker/deployed/staging/api/config.json
- docker/deployed/testnet/api/config.json
- docker/local/api/config.json
- internal/router/router.go
- internal/system/impl/sqlstore.go
- internal/system/impl/sqlstore_test.go
- pkg/client/client_test.go
Adds a config for the table metadata renderer: `https://render.tableland.xyz`
cc @awmuncy
> Adds SVG renderer to table metadata

- internal/system/impl/sqlstore.go
- internal/system/impl/sqlstore_test.go
- pkg/sqlstore/impl/system/store.go
- pkg/sqlstore/table.go
This PR updates the response for getting metadata in the `GET /chain/{chain_id}/tables/{table_id}` call.
Instead of returning an error, such as `"Failed to fetch metadata"` we return a response that complies to that NFT metadata standard and also an SVG to represent that visually. 
Examples: 
- Invalid chain: https://staging.tableland.network/chain/45/tables/30
- Table not found: https://staging.tableland.network/chain/69/tables/30
cc @andrewxhill
> Adds SVG rendering when metadata call can't find the table

- tableland-openapi-spec.yaml
There are a few differences between the open api spec file and the new methods to help with table discovery.
> Match open api spec file with service

- pkg/client/client.go
- pkg/client/client_test.go
- pkg/client/networks.go
This provides easier client configuration using hard coded information about the networks and contract addressees available. Also adds support for non-relayed write queries and rpc calls to validate write queries.
> Add support for networks, direct write queries, validate

- go.mod
- go.sum
- pkg/parsing/impl/validator.go
- pkg/parsing/impl/validator_test.go
- pkg/parsing/query_validator.go
Updates SQL parser to the most recent version which enforces the following rule from [SQL spec ](https://docs.tableland.xyz/sql-specification#9e191076e01b4ac5a24d684060b9dc49)in the parser: Each table in Tableland may have at most one PRIMARY KEY.
The error behavior of the parser changed a bit as explained in the [PR](https://github.com/tablelandnetwork/go-sqlparser/pull/11). So, there are some changes in this PR to reflect the change in that behavior.
> Parser update

- .github/workflows/test.yml
Bump the version to the latest two releases for the GH action that runs the tests.
In particular, testing for Go 1.19 is important now that we use it for Dockerfiles.
> gha: bump Go version used for tests

- tableland-openapi-spec.yaml
Looks like the validateWriteQuery endpoint was missing from the comment that describes the endpoints.   This adds it in the same style as the other endpoints
> Add missing rpc endpoint to spec

- .golangci.yml
- Makefile
- internal/router/controllers/infra.go
- internal/router/controllers/user_test.go
- internal/router/middlewares/ratelim_test.go
- internal/router/router.go
- internal/system/impl/mock.go
- internal/tableland/impl/mesa.go
- internal/tableland/impl/mesa_test.go
- pkg/client/client.go
- pkg/client/client_test.go
- pkg/eventprocessor/eventfeed/impl/eventfeed.go
- pkg/eventprocessor/impl/eventprocessor_test.go
- pkg/eventprocessor/impl/executor/impl/executor_test.go
- pkg/eventprocessor/impl/executor/impl/txnscope_runsql_test.go
- pkg/logging/logging.go
- pkg/nonce/impl/simpletracker.go
- pkg/nonce/impl/tracker_test.go
- pkg/sqlstore/impl/system/store.go
Updated so `make lint` uses the current `golangci-lint` version `1.49.0`. 
With `golangci-lint` version `1.49.0`, and now using Go 0.19, the `revive` linter is quite powerful. I configured `golangci-lint` to use the recommended revive settings listed at https://github.com/mgechev/revive#recommended-configuration, but disabled the `package-comments` rule because I don't feel like I can provide meaningful package comments in one sweep right now. If we want to start using package comments, I'd say we should put the proper effort in where/when necessary, then we can enable the rule.
> Update golangci-lint version, revive config, fixes

- pkg/eventprocessor/eventfeed/impl/eventfeed.go
Looking at the logs I see this error message `sql: transaction has already been committed or rolled back`, which looked odd.
That message corresponds to `sql.ErrTxDone`, which signals that you can't do any further operation in the transaction since it was already finished (Committed or Rollbacked).
Our idiom was fine since it is a good practice always to defer a rollback to cover any error-early-return case, so we roll back the transaction. If the execution was fine (and thus Committed), Rollback is a noop. 
The problem here was that it only makes sense to log the Rollback error if isn't `sql.ErrTxDone` (which signals that there was a commit since all went fine).
> eventfeed/eventspersistance: exclude incorrect error log

- cmd/api/config.go
- cmd/api/main.go
- docker/deployed/staging/api/config.json
- docker/deployed/testnet/api/config.json
- docker/local/api/config.json
- internal/tableland/impl/mesa_test.go
- pkg/client/client_test.go
- pkg/eventprocessor/eventfeed/eventfeed.go
- pkg/eventprocessor/eventfeed/impl/eventfeed.go
- pkg/eventprocessor/eventfeed/impl/eventfeed_test.go
- pkg/eventprocessor/impl/eventprocessor_test.go
- pkg/sqlstore/impl/system_store_instrumented.go
This PR changes the mechanics of how `EventFeed` works. We detected new blocks using a subscription-api to be notified about new blocks in the chain. That's fine since it's an efficient way to know when to get recent events from chains.
It has a downside related to Ethereum node API calls, mostly in supported chains with fast block production, such as Optimism chains. In those cases, we're having a lot of activity in these subscriptions and other downstream API calls with reactivity that isn't required.
This PR switches the mechanics to do polling with a configurable delay which means:
1) The validator operator can put a cap on how fast to react getting new blocks to have an efficient tradeoff. For example, receiving a stream of new blocks of 10 blocks per second is inefficient since 99% …
> Change EventFeed chain sync mechanics to impact Ethereum node SaaS costs

- docker/observability/grafana/provisioning/dashboards/validator-dashboard.json
- go.mod
- go.sum
- pkg/nonce/impl/tracker.go
One of our node operators reported a negative balance in the dashboard for his wallet:
The problem is that we were converting `big.int` to `int64` and the balance was wrapping around and becoming negative. 
The solution was to treat the balance as `gWei` and not `wei` by removing the trailing 9 digits. 
cc @carsonfarmer 
---
This PR also updates the parser to the version that disallows the functions:
- date
- time
- datetime
- julianday
- unixepoch
- strftime
See [PR](https://github.com/tablelandnetwork/go-sqlparser/pull/12).
> Fixes bug in wei balance metric and updates parser

- cmd/api/main.go
- docker/local/api/config.json
`local` was failing because the default 0 for `HashCalculationStep` config is not accepted. This PR adds a value to `local/api/config.json` to avoid 0 being the default. 
cc @joewagner
> Adjust local config to add hash calculation step

- pkg/sqlstore/impl/system/store.go
Signed-off-by: Bruno Calza <brunoangelicalza@gmail.com>
> fix: early return missing when getting node id

- .github/workflows/test.yml
- .gitignore
- Makefile
- cmd/api/main.go
- cmd/foo/main.go
- internal/system/impl/sqlstore_test.go
- internal/tableland/impl/mesa_test.go
- pkg/client/client_test.go
- pkg/eventprocessor/eventfeed/eventfeed.go
- pkg/eventprocessor/eventfeed/impl/sqlitechainclient/sqlitechainclient.go
- pkg/eventprocessor/impl/eventprocessor.go
- pkg/eventprocessor/impl/eventprocessor_replayhistory_test.go
- pkg/eventprocessor/impl/eventprocessor_test.go
- pkg/eventprocessor/impl/executor/impl/blockscope.go
- pkg/eventprocessor/impl/executor/impl/executor.go
- pkg/eventprocessor/impl/executor/impl/executor_test.go
This PR includes a new test that replays all Tableland history and checks that each chain's last Tableland state hash matches a defined expected hash.
---
This test aims to detect two main problematic situations that are hard to see via PRs:
**Detect non-deterministic execution**
If any event execution isn’t deterministic, it will create a snowball effect leading to a different state hash that won’t match the expected one.
Any validator that syncs from scratch should always arrive at the same state hash in each chain after it syncs to the tip. This test enforces this invariant.
**Detect if fixes or new features unintentionally change history**
If we make a bug fix or implement a new feature, there’s the chance that, under these new rules, the execution of historical events can lead to a …
> Replay of historic production Tableland events 

- cmd/api/main.go
- internal/system/impl/sqlstore_test.go
- internal/tableland/impl/mesa_test.go
- pkg/backup/backuper.go
- pkg/client/client_test.go
- pkg/dbhash/dbhash_test.go
- pkg/eventprocessor/eventfeed/impl/eventfeed_test.go
- pkg/eventprocessor/impl/eventprocessor_replayhistory_test.go
- pkg/eventprocessor/impl/eventprocessor_test.go
- pkg/eventprocessor/impl/executor/impl/executor_test.go
- pkg/nonce/impl/tracker_test.go
- pkg/sqlstore/impl/system/store.go
- pkg/sqlstore/impl/user/store.go
- pkg/sqlstore/impl/user/store_test.go
- pkg/tables/impl/ethereum/client_test.go
- pkg/telemetry/storage/db.go
- pkg/telemetry/storage/db_test.go
- tests/sqlite3.go
This PR fixes a bug where we didn't properly close database connections used for database migrations.
I've checked in my local validator and tested that with/without this change, my WAL file does/doesn't get checkpointed.
I've also removed the `MaxIdleConns(0)`, which always forces us to open a new connection, which we've seen has a considerable hit on the overall performance of the validator. Let's get back to square one now that this _should_ be fixed and stop paying a performance penalty that didn't even fixed/alleviated the problem.
Note that we're trying to avoid as much as possible having any background goroutine to force checkpointing and let the natural behavior of SQLite be enough. Considering we found the source of the problem, we'll see now if that's the case.
Closes #312.
See …
> Fix WAL checkpoint starvation due to unclosed migration connections

- buildinfo/buildinfo.go
- cmd/api/config.go
- cmd/api/main.go
- docker/deployed/staging/api/config.json
- docker/deployed/testnet/api/config.json
- internal/chains/chains.go
- pkg/eventprocessor/eventprocessor.go
- pkg/eventprocessor/impl/eventprocessor.go
- pkg/telemetry/chainscollector/chainscollector.go
- pkg/telemetry/metrics.go
- pkg/telemetry/storage/db.go
- pkg/telemetry/storage/db_test.go
- pkg/telemetry/telemetry.go
- pkg/telemetry/telemetry_test.go
This PR adds two new metrics to the optional telemetry collection:
- The Git summary of the validator binary: This will help understand if validators are running old versions.
- Last executed block number per chain: this will help to understand if validators have some healthiness problem syncing chains, lagging behind; we could infer syncing speeds or liveness since the metric is published at a fixed time-frequency.
This was tested in staging, and it's working correctly.
This is part of the objective to add optional telemetry reporting in validators.
The implementation has two main parts:
1) Git summary metrics: this is published once when the validator spins up. 
2) Last executed block number: this is done by a new telemetry sub-package, collecting the information in all `chainStacks`, …
> Telemetry: add binary git summary & last executed block number per chain id

- internal/router/middlewares/otelhttp.go
This PR solves, hopefully, the last breaking change of OTEL default attributes behavioral change.
In the testnet dashboard, some tiles don't show information:
In the staging dashboard I deployed this PR and it shows data correctly.
https://github.com/tablelandnetwork/go-tableland/pull/323
Luckily, after digging into the `otelhttp`, I saw that you can inject custom labels if you do an extra middleware wrapping.
It'll become clear while seeing the code.
NA
> otelhttp: add service name

- internal/system/impl/sqlstore_instrumented.go
- internal/tableland/impl/mesa_instrumented.go
- pkg/parsing/impl/validator_instrumented.go
- pkg/sqlstore/impl/system_store_instrumented.go
- pkg/sqlstore/impl/user_store_instrumented.go
Add `metrics.BaseAttrs` to all the instrumentation middleware that registers metrics for stores/apis.
Tested in staging.
NA
NA
NA
> instrumented: add metrics.BaseAttrs 

- pkg/backup/restorer/restorer.go
- pkg/backup/restorer/restorer_test.go
A small improvement in the backup restoration process to consider that a database could already exist and contain local information such as node id and pending transactions
The backup restorer was deleting the node id and pending txs from the backup database. But that turns out to be a bad idea. The node that is bootstrapping from a backup file may have pending txs in its local databases, and it already has a node id. Deleting those means that we lose track of the pending txs, and the node is forced to generate a new node id, which is not ideal.
- We check if a database already exists
- If a database already exists, rename it to another name
- Create a new database that is a copy of the backup
- Delete information from `system_pending_tx` and `system_id` tables
- Copy information of …
> Improves the backup restorer to consider an existing database

- cmd/api/config.go
TL;DR; uconfig enforces that all flags be defined in the config struct
See the discussion in #378 for more detail.
> Fix #378 allow config dir path as command flag

- .golangci.yml
- cmd/api/config.go
- cmd/api/main.go
This PR does a general refactor in `main.go` to organize our wires better. The main goal is to have a `func main()` that's more understandable.
Closes #302 
The `main()` function is now more high-level, always calling `create***()` functions that will create modules. These methods usually return a `close***` variable, a `moduleCloser` function to be used when Ctrl+C is received.
To clarify things, I've extracted anonymous structs used in `config.go` to be non-anonymous.
NA
> main: refactor wirings

- internal/router/controllers/user.go
- internal/router/middlewares/contextkeys.go
- internal/router/middlewares/logging.go
- internal/router/rpcservice/rpcservice.go
- pkg/telemetry/metrics.go
- pkg/telemetry/publisher/publisher.go
- pkg/telemetry/publisher/publisher_test.go
- pkg/telemetry/storage/db.go
- pkg/telemetry/storage/db_test.go
- pkg/telemetry/telemetry.go
Starts collecting read query data. Every time we receive a read query, either from REST or JSON RPC, we save the SQL statement, the IP Address, and the formatting options as a metric that will be shipped to BigQuery to be analyzed. 
Close #319 
Most of the implementation is creating the metric and adjusting things so the metric can be collected. 
Other than that, we are now deleting metrics older than 7 days to avoid storage problems. 
NA
> Collects read query metrics 

- .github/workflows/deploy.yml
- docker/deployed/staging/api/config.json
- pkg/eventprocessor/eventfeed/impl/analytics.go
- pkg/eventprocessor/eventfeed/impl/eventfeed.go
- pkg/telemetry/metrics.go
- pkg/telemetry/storage/db.go
- pkg/telemetry/storage/db_test.go
- pkg/telemetry/telemetry.go
- pkg/telemetry/telemetry_test.go
Closes #307
Our current Retool dashboard is querying our cloud validator directly, which isn't convenient since:
- We're adding analytics load to our main validator.
- The way data is stored in SQLite isn't suitable for analytics.
- Since SQLite is a local database, we needed to add an extra infrastructure piece (postlite) to have a PostgreSQL wire format.
By sending the `system_evm_events` and `system_evm_blocks` as events, we can leverage saving this information in BigQuery and use it as the database for Retool. We'll continue to do other ad-hoc analytics apart from the main dashboard, so we can keep taking advantage of having access to this data to do heavy queries.
After this PR is running in `main` for some days (so we have some data), I'll change the Retool dashboard to start using …
> analytics: send detected Tableland events and chain blocks as telemetry data

- .gitignore
- cmd/metricshub/Makefile
- infra/.gitignore
- infra/Readme.md
- infra/bootstrap.sh
- infra/main.tf
This is another iteration in our current draft Terraform deployment for gcloud.
The main goal is to automate as much as possible any new validator with this setup:
- Optimize boot disk to use minimal version, and bump size.
- Remove not needed firewall rules considering our latest BQ movements for analytics
- Include crontab rules for backuping, snapshot uploading, and docker pruning.
- Generalize the script that was previously hardcoding `testnet`, to a script that will automatically know where to put target files by using `uname -m` to derive if this is a `staging`, `testnet` or `mainnet` deployment. To avoid an extra Terraform var.
We're in the process of deploying new validators due to the testnet and mainnet network splits.
I'll explain in PR comments when ready.
NA
> infra/terraform: automate more tasks & fixes

- cmd/api/config.go
- cmd/api/main.go
- docker/deployed/staging/api/config.json
- docker/deployed/testnet/api/config.json
- docker/local/api/config.json
- internal/router/router.go
- internal/system/impl/sqlstore.go
- internal/system/impl/sqlstore_test.go
- pkg/client/client_test.go
- pkg/sqlstore/table.go
Adds `animation_url` property to the response of Table's metadata call `GET /chain/{chainID}/tables/{id}`
Closes #326 
cc @awmuncy 
An HTML app (light version of the dashboard) pointed by `animation_url` address will be rendered on most NFT marketplaces when the Table NFT details page is opened. 
Adds a new config `AnimationRendererURI`. In `testnet` it points to `https://render.tableland.xyz/anim/`. In other envs it's just an empty string, which means the `animation_url` won't be shown. 
n/a
> Adds animation_url to table's metadata

- cmd/api/main.go
It was passing the wrong variable to the router. 
When the PR #332 was rebased the code was wrongly merged.
> fix: pass the right animation config value to router

- internal/system/impl/sqlstore.go
- internal/system/impl/sqlstore_test.go
This PR disables `animation_url` for testnet chains.
**Note: This PR deployment isn't confirmed yet. If the decision is confirmed, we can review+merge, if not we can close it.**
There's a current problem in OpenSea for testnets that is currently under investigation. As a workaround, we're disabling `animation_url` for testnets.
NA
NA
> animationurl: temporal workaround for OpenSea problem

- internal/router/controllers/system.go
It avoids HTML escaping in the `GetTables` API.
This was asked to avoid escaping characters in field values that contain URLs with ampersand, e.g: `"animation_url":"https://render.tableland.xyz/anim/?chain=137\u0026id=29"`
NA
NA
> Avoid html escaping in GetTable API

- .github/workflows/binaries.yml
- .github/workflows/deploy.yml
This PR includes a new Github Action that is run when a tag is created, which:
- Creates binaries for `linux/amd64`, `windows/amd64`, and `darwin/amd64`
- Create Docker images for `amd64` and `arm64`.
Closes #365.
**Note: This PR is ready for review, but I'll keep it in draft until Bruno returns.**
This is part of our work to provide more options to validators apart from building from source.
Building these binaries isn't as easy as using the cross-compiling feature of Go, since we rely on CGO, which complicates things quite a bit. In particular, for M1 binaries since Github Actions doesn't have `arm64` VMs (at least, yet). I gave it a shot to a QEMU setup to simulate an `arm64` arch on top of `amd64` It was pretty good, but unfortunately, the GCC version that M1 needs is a custom XCode …
> CI: generate binaries and Docker images

- go.mod
- go.sum
- pkg/eventprocessor/impl/executor/impl/txnscope.go
- pkg/eventprocessor/impl/executor/impl/txnscope_runsql.go
Updates parser with new custom function implementation and improve the error handling
- See https://github.com/tablelandnetwork/go-sqlparser/pull/43
- Also, when a query cannot be resolved we need to return `errorQueryExecution` error so that the execution pipeline does not halt
> Updates parser with new custom function implementation

- .github/workflows/binaries.yml
This pr adds a job to the end of the binaries.yml workflow.  The job is setup to wait until the building of the binaries is finished, then it will trigger a [workflow in the js-validator repo](https://github.com/tablelandnetwork/js-validator/blob/main/.github/workflows/release-pr.yml).
The workflow that is triggered in the js-validator repo does a few things:
1. It creates a Pull Request to add binaries that were released here to the js-validator repo.
2. In the PR it will also update the version of js-validator to match the go-tableland release.
3. If the js-validator PR is merged, the binaries are automatically published to npm under a version matching the go-tableland release.  Doing this will trigger dependabot enabled downstream consumers to be alerted to the new version.
See …
> add remote workflow trigger binaries.yml

- .github/workflows/binaries.yml
The name of the remote workflow that is triggered when the release binaries are build changed.  This updates the name to enable triggering js-validator's workflow.
After #429 was merged the name of the remote workflow file changed.  This PR updates the name.
> Fix name of remote workflow in binaries.yml

- internal/system/impl/sqlstore_test.go
- pkg/sqlstore/impl/system/store.go
When getting the schema of a table we need to parse the statement that is stored in SQLite. Sometimes that statement may come with an `AUTOINCREMENT` (because of the protocol rules that add the `AUTOINCREMENT` keyword automatically when an `INTEGER PRIMARY KEY` is found). However, the `AUTOINCREMENT` keyword is not parsable. So we're getting an error. 
Closes #428 
Simply remove the `AUTOINCREMENT` before parsing.
I don't think removing keywords that are not parsable such as `STRICT` and `AUTOINCREMENT` is a good long-term approach. But this is good enough to solve the `bug`. 
This is also related to https://github.com/tablelandnetwork/go-sqlparser/issues/41. It is kind of weird that the `String` method produces and string that is not compliant with the Tableland SQL. But that's more a …
> fix: get schema was not parsing statements with autoincrement 

- .github/workflows/binaries.yml
Fixes the input of the `js-release` job
When we created the [v1.0.0-beta-1](https://github.com/tablelandnetwork/js-validator/commit/5b19f99824aaab2bcb8096553d85426ed7773bdc) release, the`js-release` job was triggered and it [failed](https://github.com/tablelandnetwork/go-tableland/actions/runs/3949156639/jobs/6760153189):
```
Error: Unexpected inputs provided: ["release_version"]
```
Looking at the [commit](https://github.com/tablelandnetwork/js-validator/commit/5b19f99824aaab2bcb8096553d85426ed7773bdc) history of `js-validator` repo, looks like the input `release_version` was changed to `validator_version`. 
cc @asutula @joewagner
> fix: wrong input js release job

- pkg/parsing/impl/validator.go
The caret was missing in the regex that validates the table's name
The regex must match the full table name. The same rule is used in the parser [helper](https://github.com/tablelandnetwork/go-sqlparser/blob/main/helpers.go#L87).
> adds missing caret to regex

- cmd/api/config.go
- pkg/client/v1/client_test.go
- tests/fullstack/fullstack.go
This updates the default value for the GatewayConfig.ExternalURIPrefix and updates the tests.
> Update the tests to reflect new dns values

- .dockerignore
This PR changes the `.dockerignore` file that removes some files that are part of the repo when building the Docker images. This causes some problems for the "dirtyness" of the git repo in the Docker scratchpad, which ultimately makes the reported git version by te validator to always be `*-dirty`.
Tested with a beta release, and [it's working correctly now](https://tableland.network/api/v1/version).
NA.
NA.
NA
> dockerignore: avoid excluding files that are part of the repo

- internal/router/middlewares/ratelim.go
The legacy API (JSON-RPC) will exist for a limited time. After inspecting our Grafana dashboards, I noticed that we still have some activity. This PR adds a log line in the right place to print more details.
If we know who is still using the old RPC, we can ping them to start using the latest API since JSON-RPC will soon deprecate.
NA
NA
NA
> logs: add warn log to detect calls to legacy RPC

- cmd/healthbot/config.go
- cmd/healthbot/counterprobe/counterprobe.go
- cmd/healthbot/counterprobe/counterprobe_test.go
- cmd/healthbot/main.go
- docker/deployed/testnet/healthbot/config.json
- pkg/client/v1/writequery.go
- pkg/tables/impl/ethereum/client.go
- pkg/tables/tables.go
The Go client (`client/v1`) now accepts an option to amplify the internal suggested gas price it gets from the Ethereum API. If no option is used, the behavior is the same as today (not a breaking change). But now the user can bump the price if he wants the transaction to have a higher priority or avoid "gas refill".
Additionally, we allow a new configuration knob in healthbot so we can specify if any chain will have a gas prices bump.
The Ethereum Goerli chain sometimes have quick spikes in gas prices, which doesn't play nice with `SuggestedGasPrice(...)`. 
NA
NA
> client/v1: allow suggested gas price multiplier & use it in healthbot for Ethereum Goerli

- Makefile
- pkg/backup/pruner_test.go
golangci-lint has been broken when using Go 1.19.x giving some `Can't run linter goanalysis_metalinter: goimports: can't extract issues from gofmt diff output` error. They just released an update that fixes that. It introduced a lint failure I fixed.
> Update golangci-lint, lint fix

- pkg/parsing/impl/validator.go
The validator parser check was not considering compound select as a possible read query.
@asutula was trying to execute the compound [query](https://testnets.tableland.network/api/v1/query?statement=select%0A%20%20%20%20rig_id%2C%0A%20%20%20%20%27display_type%27%20as%20display_type%2C%0A%20%20%20%20case%20deal_number%0A%20%20%20%20%20%20when%201%20then%20%27deal%201%27%0A%20%20%20%20%20%20when%202%20then%20%27deal%202%27%0A%20%20%20%20end%20trait_type%2C%0A%20%20%20%20deal_id%20as%20value%0A%20%20from%20deals_80001_5600%0A%20%20union%0A%20%20select%20%0A%20%20%20%20rig_id%2C%0A%20%20%20%20display_type%2C%0A%20%20%20%20trait_type%2C%0A%20%20%20%20value%20%0A%20%20from%20rig_attributes_80001_5599%3B) and that returned an error. That query is allowed and should be executed. It is not …
> fix: read query validation not considering compound select 

- cmd/api/main.go
- docker/deployed/staging/api/config.json
- docker/deployed/testnet/api/config.json
- docker/local/api/config.json
This PR will turn off all transaction relaying and enable upgrading the registry contract to disallow contract owner calling functions on behalf of eoas. https://github.com/tablelandnetwork/evm-tableland/pull/307
This is a first step in shutting down and removing the legacy JSON-RPC API. #460 
The implementation is fairly simple.  The config files have all been changed so the `AllowTransactionRelay` value is false.  
Along with changing the config files, this somewhat redundantly forces all `ChainStack`s so`AllowTransactionRelay` value is false.
> set AllowTransactionRelay to false in all configs

- .github/workflows/binaries.yml
This PR fixes the problem that occurred while generating the [v1.0.1-beta-4](https://github.com/tablelandnetwork/go-tableland/actions/runs/4204737716/jobs/7376801645) release. 
For some reason, the `go build` on `ubuntu-latest` was failing with the message 
```
error obtaining VCS status: exit status 128
Use -buildvcs=false to disable VCS stamping.
```
I could do `go build -buildvcs=false ./cmd/api` to make the workflow work again but that error usually happens when there's something misconfigured in the `.git` repository. 
I'm unsure what has changed since the last `v1.0.1-beta-3` release. But after some debugging (I added a `git status` in the middle of the build), I noticed that [the real issue was](https://github.com/tablelandnetwork/go-tableland/actions/runs/4245120022/jobs/7380200498 …
> Fixes binaries workflow

- Makefile
Fixes the command `make gen-api-v1` to work on M1 Mac.
The command was not working because the docker image `swaggerapi/swagger-codegen-cli` was not built for `arm64` platform. 
Closes #468 
- I built a new image for both platforms by doing the following:
```
git clone https://github.com/swagger-api/swagger-codegen/ && cd swagger-codegen
git checkout v3.0.41
./run-in-docker.sh mvn clean package
cd modules/swagger-codegen-cli
docker buildx build \
--platform=linux/amd64,linux/arm64 \
-f Dockerfile \
--push \
-t textile/swagger-codegen-cli:3.0.41 \
-t textile/swagger-codegen-cli:latest \
.
```
- Also, I've put the cleanup commands after code generation to be run inside the docker container and not outside because the `sed` command in Mac is different from the one running in Linux. 
- Check …
> Fixes api gen command to work on M1

- .github/workflows/binaries.yml
- .github/workflows/review.yml
- .github/workflows/test.yml
- go.mod
I noticed that the binaries.yml workflow failed with a message saying "Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/setup-go@v2." https://github.com/tablelandnetwork/go-tableland/actions/runs/4204737716
I'm not sure if upgrading the setup-go action to v3 will fix the issue that caused the binaries build to fail, but seems like a good thing to do anyway. 
n/a
n/a
n/a
> upgrade the actions/setup-go action

- docker/deployed/mainnet/api/config.json
- pkg/client/chains.go
- pkg/eventprocessor/eventfeed/impl/eventfeed.go
This PR integrates the validator with the Arbitrum Nova network. 
Arbitrum Nova is a [Arbitrum public chain](https://developer.arbitrum.io/public-chains) built on top of the [AnyTrust](https://developer.arbitrum.io/inside-anytrust). It is cheaper than other rollups because it doesn't rely on the L1 chain for data availability. Instead, the DA is guaranteed by a committee. It means that in practice tableland's create and update queries could be performed for ~ $0.001 per query. It makes the tableland network with Arbitrum highly affordable for use cases that have a high write volume.
This PR simply adds a new mainnet config. The config includes an endpoint to fetch events from the Arbirtum Nova blockchain. We will use a `quicknode` endpoint for this purpose. The `eventfeed` connects with …
> Add arbitrum nova config

- go.mod
- go.sum
- pkg/client/v1/client_test.go
- pkg/eventprocessor/impl/eventprocessor_replayhistory_test.go
- pkg/parsing/impl/validator_test.go
Bumps the parser to the latest version. This version includes:
- [shorter string output for parsed statements](https://github.com/tablelandnetwork/go-sqlparser/pull/45)
- [fixes bug on upsert walk](https://github.com/tablelandnetwork/go-sqlparser/pull/49)
> Bumps the parser

- internal/gateway/gateway.go
- internal/gateway/gateway_test.go
- internal/router/controllers/controller_test.go
- pkg/client/v1/client_test.go
This updates the external_url value of table metadata to use the new api endpoints, which is causing issues rendering the table nft on some of the market places.
> Replace old table external_url

- .github/workflows/binaries.yml
- goreleaser.yml
This a fix for issue #535 
When we upgraded the binary build process to include builds for arm64 (i.e. apple silicon), the name template of the binary files was changed to include a short hash of the commit that the build is targeting.
This caused an issue in the build process of the [js-validator repo](https://github.com/tablelandnetwork/js-validator/blob/main/src/build.ts#L64).
The TL;DR; of the js-validator issue is that the script to download and unpack the go-tableland release doesn't have access to the short commit hash that now makes up part of the url where the binary is located.
This fix simply removes the commit hash from the file name.  If keeping the commit hash is important, we can close this PR and find a way for the js-validator build script to get the commit hash during …
> remove commit hash from binary names

- go.mod
- go.sum
- pkg/eventprocessor/impl/eventprocessor_replayhistory_test.go
Updates the parser 
When an identifier or alias had a dot, the stringification of the AST was producing an invalid statement.
See https://github.com/tablelandnetwork/go-sqlparser/pull/52
> updates parser

- cmd/api/main.go
- internal/gateway/gateway.go
- internal/gateway/impl/gateway_store.go
- internal/router/controllers/apiv1/model_transaction_receipt.go
- internal/router/controllers/controller.go
- internal/router/controllers/controller_test.go
- internal/tableland/impl/tableland_test.go
- pkg/database/db/models.go
- pkg/database/db/receipt.sql.go
- pkg/database/migrations/005_receipttableids.down.sql
- pkg/database/migrations/005_receipttableids.up.sql
- pkg/database/migrations/migrations.go
- pkg/eventprocessor/eventprocessor.go
- pkg/eventprocessor/impl/eventprocessor.go
- pkg/eventprocessor/impl/eventprocessor_replayhistory_test.go
- pkg/eventprocessor/impl/eventprocessor_test.go
- pkg/eventprocessor/impl/executor/executor.go
- pkg/eventprocessor/impl/executor/impl/blockscope.go
- pkg/eventprocessor/impl/executor/impl/txnscope.go
- pkg/tables/tables.go
- This PR implements the [new API spec (1.0.1)](https://github.com/tablelandnetwork/docs/pull/112).
Fixes #522 
- Most of the changes are to reflect the passage of the `TableIds` data through multiple layers
- Adds a new migration to store `table_ids` in the `system_txn_receipts` table
- It's hard to create an e2e test of this feature. I've added a test at the controller level with a mocked gateway.
> fixes the response of receipt api call

- docker/deployed/testnet/healthbot/config.json
Removes Arbitrum Goerli and Optimism Goerli healthbot probes
It got too hard to fund those wallets. It's not making sense to have those probes.
> removes healthbot probes for goerli chains

- cmd/healthbot/config.go
- cmd/healthbot/main.go
- docker/deployed/testnet/healthbot/config.json
Follow up PR to #580 
It adds the `healthbot` configuration for the calibration net. Due to the 2k block history constraint, we needed to deploy the `healthbot` table manually after deploying the validator.
> Add healthbot config for calibration

- internal/router/controllers/controller.go
- internal/router/controllers/controller_test.go
This PR ensures that we don't return 404 from the Gateway API if the table is empty i.e. there are no rows in the table.
[GOT-111] [JST-28]
> [got-111] change empty /query status to 200

- docker/deployed/testnet/api/config.json
- pkg/eventprocessor/impl/webhook.go
- pkg/eventprocessor/impl/webhook_test.go
Adds more context to webhooks content by adding hyperlinks for transactions, table ids and chain ids. Fixes GOT-108
To add links to the tableland docs, and block explorers I have stored these links in the webhooks package against their corresponding chain ids.
> Reformat webhooks

- pkg/eventprocessor/eventfeed/impl/eventfeed.go
Increase FilterLogs call timeout because glif is timing out
> increase filter logs timeout

- cmd/api/config.go
- cmd/api/main.go
- docker/deployed/mainnet/api/config.json
- docker/deployed/staging/api/config.json
- docker/deployed/testnet/api/config.json
- internal/router/middlewares/ratelim.go
- internal/router/middlewares/ratelim_test.go
- internal/router/router.go
- tests/fullstack/fullstack.go
This PR adds a new config for the HTTP rate limiter: `ApiKey`. With that, authorized clients (clients that provide the same key) will not be rate limited. 
Our Studio application is being rate limited fairly easily. 
Adds a new config to be configured via env. Makes a change to the rate limiter middleware to ignore the authorized clients
> allows authorized clients to bypass rate limiter

- README.md
Updates README with a fix for a broken anchor link (the docs site imports this README and always complains about it) and also the year in the README license section.
> docs: update README with OP sepolia
